### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by doing-cr7** [fengxsong/aliyun_exporter#1]
没有example.yaml文件呀。
可以直接使用ayli的aliyun的exporter的yaml文件吗

**Comment by doing-cr7** [comment]
volumes:
    - ../config.yaml:/etc/aliyun-exporter.yaml
这个config.yaml没找到

**Comment by fengxsong** [comment]
> volumes:
> - ../config.yaml:/etc/aliyun-exporter.yaml
> 这个config.yaml没找到

配置在这里可以找到 https://github.com/fengxsong/aliyun-exporter/blob/main/deploy/aliyun-exporter/values.yaml#L22
或者是通过子命令`list-metrics`和`print-config`打印示例config.yaml

**Comment by doing-cr7** [comment]
![image](https://user-images.githubusercontent.com/63889450/116026000-5660a400-a684-11eb-96ad-aacfa44546d1.png)
这个是错误

https://github.com/ylmcr7/my-project/blob/main/config.yaml
这个是我的config.yaml文件。

**Comment by doing-cr7** [comment]
我的config.yaml格式文件对吗？

**Comment by doing-cr7** [comment]
可以启动，但是我并没有使用aliyun的redis，为什么会拿到aliyun的redis数据呢？
![image](https://user-images.githubusercontent.com/63889450/116036699-abf37b80-a699-11eb-8378-c8741f20e619.png)

**Comment by fengxsong** [comment]
> 可以启动，但是我并没有使用aliyun的redis，为什么会拿到aliyun的redis数据呢？
> 
> ![image](https://user-images.githubusercontent.com/63889450/116036699-abf37b80-a699-11eb-8378-c8741f20e619.png)
> 
> 

这个是因为你的配置文件里边包含了redis的项，exporter本身并不知道对应的账号里边是否有redis实例，如果确定不需要或者没有实例的话，可以去掉这些监控项，减少调用aliyun cloumonitor API次数。

**Comment by fengxsong** [comment]
如果没有更多问题我就关闭issue了
