### ISSUE TITLE
请求没有返回阿里云的监控信息？？

### ISSUE THREAD

**Issue by herbiel** [fengxsong/aliyun_exporter#3]
curl http://127.0.0.1:9527/metrics
显示的都是go的？

**Comment by shuoshadow** [comment]
我也部署了，我是有数据的，会不会是你的config配置错误呢，可以把debug日志打开看看日志

**Comment by fengxsong** [comment]
是的，如果配置里边没有指定要去抓去的指标的话，默认exporter返回的就只有默认registry包含的metrics。
