### ISSUE TITLE
指标的lable能包含实例自定义的名称吗

### ISSUE THREAD

**Issue by shuoshadow** [fengxsong/aliyun_exporter#4]
cloudmonitor_acs_slb_dashboard_UpstreamRt{container="aliyun-exporter", endpoint="http", instance="192.168.98.59:9527", instanceId="lb-bp1cxok9xxxxxxx", job="aliyun-exporter", namespace="monitoring", pod="aliyun-exporter-575d7c7df4-z95rq", port="443", protocol="https", service="aliyun-exporter", userId="xxxxxxx"}

现在只有一个instanceId，在做grafana的时候不方便分辨这个实例的用途，能拿到实例名称吗？

**Comment by fengxsong** [comment]
可以参考这个 https://github.com/fengxsong/aliyun-exporter/blob/main/deploy/rules.yaml#L40
通过group_left label_replace function来将instance的信息作为metrics中的lable values。

**Comment by shuoshadow** [comment]
> 可以参考这个 https://github.com/fengxsong/aliyun-exporter/blob/main/deploy/rules.yaml#L40
> 通过group_left label_replace function来将instance的信息作为metrics中的lable values。

为何我采集的指标中，并没有类似cloudmonitor_rds_instance_info之类的指标呢，我很确定我配置了instanceInfos, 并且也读到了配置的内容，阿里云的ak也有读的权限

**Comment by shuoshadow** [comment]
> 可以参考这个 https://github.com/fengxsong/aliyun-exporter/blob/main/deploy/rules.yaml#L40
> 通过group_left label_replace function来将instance的信息作为metrics中的lable values。

可以了 非常感谢

**Comment by fengxsong** [comment]
@shuoshadow 你的配置方便贴一下吗？
