### ISSUE TITLE
net/http报错

### ISSUE THREAD

**Issue by IAOTW** [fengxsong/aliyun_exporter#6]
以下报错会偶发：
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
还没有排查出原因，刚run起来容易复现

**Comment by IAOTW** [comment]
已经解决了，需要设置下超时时间
cmsClient.Client.SetReadTimeout(50 * time.Second)

**Comment by fengxsong** [comment]
@IAOTW 网络问题可能导致请求超时 还有一个如果请求太频繁会引起阿里云的限流策略。
