### ISSUE TITLE
好像不能支持polardb

### ISSUE THREAD

**Issue by herbiel** [fengxsong/aliyun_exporter#8]
好像不能支持polardb

**Comment by fengxsong** [comment]
@herbiel 不好意思，我当前没有很多时间来维护这个项目，你可以尝试下[这个](https://github.com/IAOTW/aliyun-exporter)项目，联系下他是否能帮你看看？也欢迎你给本项目贡献代码哈～

**Comment by fengxsong** [comment]
@herbiel 最新的支持了。
